name: 'CI - Build and Test'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Security Audit
      run: npm audit --audit-level=high
      
    - name: Run Tests
      run: npm test
      
    - name: Health Check Test
      run: npm run test:health

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Build Docker Image
      run: |
        docker build -t ultimate-mcp-server:ci-test .
        docker run --rm --health-cmd='curl -f http://localhost:3001/health || exit 1' ultimate-mcp-server:ci-test npm run test:health
